### ISSUE TITLE
Spends tokens even if validation check fails

### ISSUE THREAD

**Issue by hammanandre** [owigame/The-Bunny-And-The-Unicorn#11]
Spawning a unit if there is already one spends your tokens. 
So validation check fails but still expenses happen

**Comment by hammanandre** [comment]
[the line of issue](https://github.com/owigame/The-Bunny-And-The-Unicorn/blob/42d9dc5ab7805a0e62dfb5a9bed3d8f5a6bda717/Assets/Scripts/AIFramework/AIResponseManager.cs#L77)

[ine in issue](https://github.com/owigame/The-Bunny-And-The-Unicorn/blob/42d9dc5ab7805a0e62dfb5a9bed3d8f5a6bda717/Assets/Scripts/AIFramework/AIResponseManager.cs#L87)

**Comment by 4t0m1c** [comment]
Fixed
